apiVersion: v1
Kind: Deployment
metadata:
  labels:
    app: ed-beta
  name: ed-beta-deployment
  namespace: elpis-demo-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ed-beta-pod
  template:
    metadata:
      labels:
        app: ed-beta-pod
    spec:
      containers:
        - image:
          name: 'xxx'
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: xxx